---
language: node_js
node_js:
  - "4.2"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=1.13.13
  - EMBER_TRY_SCENARIO=2.0.3
  - EMBER_TRY_SCENARIO=2.4.5
  - EMBER_TRY_SCENARIO=2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-alpha

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-alpha

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^3"
  - "npm install -g bower"

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
